version: '3'

services:
  app:
    image: node:alpine
    command: sh -c "yarn install && yarn start"
    working_dir: /home/node/app
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app
    links:
      - database

  database:
    image: mongo
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
